export { ReactComponent as Camera } from './Camera.svg';
export { ReactComponent as CaretDown } from './CaretDown.svg';
export { ReactComponent as Check } from './Check.svg';
export { ReactComponent as CheckSuccess } from './CheckSuccess.svg';
export { ReactComponent as Close } from './Close.svg';
export { ReactComponent as Error } from './Error.svg';
export { ReactComponent as Heart } from './Heart.svg';
export { ReactComponent as Minus } from './minus.svg';
export { ReactComponent as PlusS } from './PlusS.svg';
export { ReactComponent as Plus } from './plus.svg';
export { ReactComponent as PlusL } from './PlusL.svg';
export { ReactComponent as PlusXL } from './PlusXL.svg';
export { ReactComponent as Share } from './Share.svg';
export { ReactComponent as Star } from './Star.svg';
export { ReactComponent as Calendar } from './Calendar.svg';
export { ReactComponent as Anonymous } from './Anonymous.svg';
export { ReactComponent as ArrowBottom } from './ArrowBottom.svg';
export { ReactComponent as ArrowLeft } from './ArrowLeft.svg';
export { ReactComponent as ArrowRight } from './ArrowRight.svg';
export { ReactComponent as ArrowTop } from './ArrowTop.svg';
import * as SocialIcons from './Social';
export { SocialIcons };
