export { ReactComponent as Camera } from './Camera.svg';
export { ReactComponent as CaretDown } from './CaretDown.svg';
export { ReactComponent as Check } from './Check.svg';
export { ReactComponent as CheckSuccess } from './CheckSuccess.svg';
export { ReactComponent as Close } from './Close.svg';
export { ReactComponent as Error } from './Error.svg';
export { ReactComponent as Heart } from './Heart.svg';
export { ReactComponent as Minus } from './minus.svg';
export { ReactComponent as PlusS } from './PlusS.svg';
export { ReactComponent as Plus } from './plus.svg';
export { ReactComponent as PlusL } from './PlusL.svg';
export { ReactComponent as PlusXL } from './PlusXL.svg';
export { ReactComponent as Share } from './Share.svg';
export { ReactComponent as Star } from './Star.svg';
export { ReactComponent as Calendar } from './Calendar.svg';
export { ReactComponent as Anonymous } from './Anonymous.svg';
export { ReactComponent as ArrowBottom } from './ArrowBottom.svg';
export { ReactComponent as ArrowLeft } from './ArrowLeft.svg';
export { ReactComponent as ArrowRight } from './ArrowRight.svg';
export { ReactComponent as ArrowTop } from './ArrowTop.svg';
export { ReactComponent as ChevronLeft } from './ChevronLeft.svg';
export { ReactComponent as ChevronRight } from './ChevronRight.svg';

export { ReactComponent as CopyLink } from './Social/CopyLink.svg';
export { ReactComponent as Facebook } from './Social/Facebook.svg';
export { ReactComponent as GooglePodcast } from './Social/GooglePodcast.svg';
export { ReactComponent as Instagram } from './Social/Instagram.svg';
export { ReactComponent as Linkedin } from './Social/Linkedin.svg';
export { ReactComponent as Pinterest } from './Social/Pinterest.svg';
export { ReactComponent as Podcast } from './Social/Podcast.svg';
export { ReactComponent as Rss } from './Social/Rss.svg';
export { ReactComponent as Soundcloud } from './Social/Soundcloud.svg';
export { ReactComponent as Spotify } from './Social/Spotify.svg';
export { ReactComponent as Stitcher } from './Social/Stitcher.svg';
export { ReactComponent as Tumblr } from './Social/Tumblr.svg';
export { ReactComponent as Twitter } from './Social/Twitter.svg';
export { ReactComponent as Vimeo } from './Social/Vimeo.svg';
export { ReactComponent as Youtube } from './Social/Youtube.svg';

// todo: should be deprecated in the next major version
import * as SocialIcons from './Social';
export { SocialIcons };