/* eslint-disable */
/*
 * DO NOT EDIT THIS FILE!
 * YOUR CHANGES WILL BE OVERWRITTEN!
 * FILE IS BASED ON .wuf/testkits/enzyme.template.ts
 * AND GENERATED BY `wuf export-teskits`
 */
import {
  enzymeTestkitFactoryCreator,
  enzymeUniTestkitFactoryCreator,
} from 'wix-ui-test-utils/enzyme';

<<<<<<< HEAD
import { inputDriverFactory } from '../components/Input/Input.driver';
export const inputTestkitFactory: (
  obj: WrapperData,
) => any = enzymeTestkitFactoryCreator(inputDriverFactory);

import { textDriverFactory } from '../components/Text/Text.driver';
export const textTestkitFactory: (
  obj: WrapperData,
) => any = enzymeTestkitFactoryCreator(textDriverFactory);

import { buttonDriverFactory } from '../components/Button/Button.driver';
export const buttonTestkitFactory = enzymeUniTestkitFactoryCreator(
  buttonDriverFactory,
);

import { statesButtonDriverFactory } from '../components/StatesButton/StatesButton.driver';
export const statesButtonTestkitFactory = enzymeUniTestkitFactoryCreator(
  statesButtonDriverFactory,
);

import { autocompleteDriverFactory } from '../components/Autocomplete/Autocomplete.driver';
export const autocompleteTestkitFactory: (
  obj: WrapperData,
) => any = enzymeTestkitFactoryCreator(autocompleteDriverFactory);

import { cardDriverFactory } from '../components/Card/Card.driver';
export const cardTestkitFactory: (
  obj: WrapperData,
) => any = enzymeUniTestkitFactoryCreator(cardDriverFactory);

import { overlappingCardDriverFactory } from '../components/OverlappingCard/OverlappingCard.driver';
export const overlappingCardTestkitFactory: (
  obj: WrapperData,
) => any = enzymeUniTestkitFactoryCreator(overlappingCardDriverFactory);

import { tabsDriverFactory } from '../components/Tabs/Tabs.driver';
export const tabsTestkitFactory: (
  obj: WrapperData,
) => any = enzymeUniTestkitFactoryCreator(tabsDriverFactory);

import { stripCardDriverFactory } from '../components/StripCard/StripCard.driver';
export const stripCardTestkitFactory: (
  obj: WrapperData,
) => any = enzymeUniTestkitFactoryCreator(stripCardDriverFactory);

import { gridDriverFactory } from '../components/Grid/Grid.driver';
export const gridTestkitFactory: (
  obj: WrapperData,
) => any = enzymeUniTestkitFactoryCreator(gridDriverFactory);

import { tooltipDriverFactory } from '../components/Tooltip/Tooltip.driver';
export const tooltipTestkitFactory: (
  obj: WrapperData,
) => any = enzymeTestkitFactoryCreator(tooltipDriverFactory);

import { iconToggleDriverFactory } from '../components/IconToggle/IconToggle.driver';
export const iconToggleTestkitFactory: (
  obj: WrapperData,
) => any = enzymeTestkitFactoryCreator(iconToggleDriverFactory);

import { likeButtonDriverFactory } from '../components/LikeButton/LikeButton.driver';
export const likeButtonTestkitFactory: (
  obj: WrapperData,
) => any = enzymeTestkitFactoryCreator(likeButtonDriverFactory);
<<<<<<< HEAD

import { paginationDriverFactory } from '../components/Pagination/Pagination.driver';
export const paginationTestkitFactory: (
  obj: WrapperData,
) => any = enzymeTestkitFactoryCreator(paginationDriverFactory);
=======
=======
const load = module => {
  const MODULE_META_KEYS = ['__esModule'];

  const moduleFields = Object.keys(module).reduce((total, key) => {
    if (!MODULE_META_KEYS.includes(key)) {
      return total.concat(module[key]);
    }
    return total;
  }, []);

  let defaultOrFirstExport;
  if (module.default) {
    defaultOrFirstExport = module.default;
  } else if (moduleFields.length === 1) {
    defaultOrFirstExport = moduleFields[0];
  } else {
    defaultOrFirstExport = module;
  }
  return defaultOrFirstExport;
};
export const buttonTestkitFactory = enzymeUniTestkitFactoryCreator(load(require('../src/Button/Button.driver')));
export const cardTestkitFactory = enzymeUniTestkitFactoryCreator(load(require('../src/Card/Card.driver')));
export const overlappingCardTestkitFactory = enzymeUniTestkitFactoryCreator(load(require('../src/OverlappingCard/OverlappingCard.driver')));
export const stripCardTestkitFactory = enzymeUniTestkitFactoryCreator(load(require('../src/StripCard/StripCard.driver')));
export const gridTestkitFactory = enzymeUniTestkitFactoryCreator(load(require('../src/Grid/Grid.driver')));
export const statesButtonTestkitFactory = enzymeUniTestkitFactoryCreator(load(require('../src/StatesButton/StatesButton.driver')));
export const autocompleteTestkitFactory = enzymeTestkitFactoryCreator(load(require('../src/Autocomplete/Autocomplete.driver')));
export const dividerTestkitFactory = enzymeTestkitFactoryCreator(load(require('../src/Divider/Divider.driver')));
export const inputTestkitFactory = enzymeTestkitFactoryCreator(load(require('../src/Input/Input.driver')));
export const tabsTestkitFactory = enzymeTestkitFactoryCreator(load(require('../src/Tabs/Tabs.driver')));
export const textTestkitFactory = enzymeTestkitFactoryCreator(load(require('../src/Text/Text.driver')));
export const tooltipTestkitFactory = enzymeTestkitFactoryCreator(load(require('../src/Tooltip/Tooltip.driver')));
>>>>>>> chore(wuf): add enzyme & protractor exports
>>>>>>> chore(wuf): add enzyme & protractor exports
