/* eslint-disable */
/*
 * DO NOT EDIT THIS FILE!
 * YOUR CHANGES WILL BE OVERWRITTEN!
 * FILE IS BASED ON .wuf/testkits/enzyme.template.ejs
 * AND GENERATED BY `wuf export-teskits`
 */
import {
  enzymeTestkitFactoryCreator,
  WrapperData,
  enzymeUniTestkitFactoryCreator,
} from 'wix-ui-test-utils/enzyme';


import { autocompleteDriverFactory } from '../components/Autocomplete/Autocomplete.driver';
export const autocompleteTestkitFactory: (
  obj: WrapperData,
) => any = enzymeTestkitFactoryCreator(autocompleteDriverFactory);

import { avatarDriverFactory } from '../components/Avatar/Avatar.driver';
export const avatarTestkitFactory: (
  obj: WrapperData,
) => any = enzymeUniTestkitFactoryCreator(avatarDriverFactory);

import { buttonDriverFactory } from '../components/Button/Button.driver';
export const buttonTestkitFactory: (
  obj: WrapperData,
) => any = enzymeUniTestkitFactoryCreator(buttonDriverFactory);

import { cardDriverFactory } from '../components/Card/Card.driver';
export const cardTestkitFactory: (
  obj: WrapperData,
) => any = enzymeUniTestkitFactoryCreator(cardDriverFactory);

import { gridDriverFactory } from '../components/Grid/Grid.driver';
export const gridTestkitFactory: (
  obj: WrapperData,
) => any = enzymeUniTestkitFactoryCreator(gridDriverFactory);

import { iconToggleDriverFactory } from '../components/IconToggle/IconToggle.driver';
export const iconToggleTestkitFactory: (
  obj: WrapperData,
) => any = enzymeTestkitFactoryCreator(iconToggleDriverFactory);

import { inputDriverFactory } from '../components/Input/Input.driver';
export const inputTestkitFactory: (
  obj: WrapperData,
) => any = enzymeTestkitFactoryCreator(inputDriverFactory);

import { likeButtonDriverFactory } from '../components/LikeButton/LikeButton.driver';
export const likeButtonTestkitFactory: (
  obj: WrapperData,
) => any = enzymeTestkitFactoryCreator(likeButtonDriverFactory);

import { overlappingCardDriverFactory } from '../components/OverlappingCard/OverlappingCard.driver';
export const overlappingCardTestkitFactory: (
  obj: WrapperData,
) => any = enzymeUniTestkitFactoryCreator(overlappingCardDriverFactory);

import { paginationDriverFactory } from '../components/Pagination/Pagination.driver';
export const paginationTestkitFactory: (
  obj: WrapperData,
) => any = enzymeTestkitFactoryCreator(paginationDriverFactory);

import { statesButtonDriverFactory } from '../components/StatesButton/StatesButton.driver';
export const statesButtonTestkitFactory: (
  obj: WrapperData,
) => any = enzymeUniTestkitFactoryCreator(statesButtonDriverFactory);

import { stripCardDriverFactory } from '../components/StripCard/StripCard.driver';
export const stripCardTestkitFactory: (
  obj: WrapperData,
) => any = enzymeUniTestkitFactoryCreator(stripCardDriverFactory);

import { tabsDriverFactory } from '../components/Tabs/Tabs.driver';
export const tabsTestkitFactory: (
  obj: WrapperData,
) => any = enzymeUniTestkitFactoryCreator(tabsDriverFactory);

import { textDriverFactory } from '../components/Text/Text.driver';
export const textTestkitFactory: (
  obj: WrapperData,
) => any = enzymeTestkitFactoryCreator(textDriverFactory);

import { textButtonDriverFactory } from '../components/TextButton/TextButton.driver';
export const textButtonTestkitFactory: (
  obj: WrapperData,
) => any = enzymeUniTestkitFactoryCreator(textButtonDriverFactory);

import { tooltipDriverFactory } from '../components/Tooltip/Tooltip.driver';
export const tooltipTestkitFactory: (
  obj: WrapperData,
) => any = enzymeTestkitFactoryCreator(tooltipDriverFactory);
