/* eslint-disable */
/*
 * DO NOT EDIT THIS FILE!
 * YOUR CHANGES WILL BE OVERWRITTEN!
 * FILE IS BASED ON .wuf/testkits/protractor.template.ejs
 * AND GENERATED BY `wuf export-teskits`
 */
import {
  protractorTestkitFactoryCreator,
  protractorUniTestkitFactoryCreator,
} from 'wix-ui-test-utils/protractor';


import { autocompleteDriverFactory } from '../components/Autocomplete/Autocomplete.protractor.driver';
export const autocompleteTestkitFactory = protractorTestkitFactoryCreator(autocompleteDriverFactory)

import { buttonDriverFactory } from '../components/Button/Button.driver';
export const buttonTestkitFactory = protractorUniTestkitFactoryCreator(buttonDriverFactory)

import { cardDriverFactory } from '../components/Card/Card.driver';
export const cardTestkitFactory = protractorUniTestkitFactoryCreator(cardDriverFactory)

import { gridDriverFactory } from '../components/Grid/Grid.driver';
export const gridTestkitFactory = protractorUniTestkitFactoryCreator(gridDriverFactory)

import { iconToggleDriverFactory } from '../components/IconToggle/IconToggle.protractor.driver';
export const iconToggleTestkitFactory = protractorTestkitFactoryCreator(iconToggleDriverFactory)

import { inputDriverFactory } from '../components/Input/Input.protractor.driver';
export const inputTestkitFactory = protractorTestkitFactoryCreator(inputDriverFactory)

import { likeButtonDriverFactory } from '../components/LikeButton/LikeButton.protractor.driver';
export const likeButtonTestkitFactory = protractorTestkitFactoryCreator(likeButtonDriverFactory)

import { overlappingCardDriverFactory } from '../components/OverlappingCard/OverlappingCard.driver';
export const overlappingCardTestkitFactory = protractorUniTestkitFactoryCreator(overlappingCardDriverFactory)

import { paginationDriverFactory } from '../components/Pagination/Pagination.protractor.driver';
export const paginationTestkitFactory = protractorTestkitFactoryCreator(paginationDriverFactory)

import { statesButtonDriverFactory } from '../components/StatesButton/StatesButton.driver';
export const statesButtonTestkitFactory = protractorUniTestkitFactoryCreator(statesButtonDriverFactory)

import { stripCardDriverFactory } from '../components/StripCard/StripCard.driver';
export const stripCardTestkitFactory = protractorUniTestkitFactoryCreator(stripCardDriverFactory)

import { tabsDriverFactory } from '../components/Tabs/Tabs.driver';
export const tabsTestkitFactory = protractorUniTestkitFactoryCreator(tabsDriverFactory)

import { textDriverFactory } from '../components/Text/Text.protractor.driver';
export const textTestkitFactory = protractorTestkitFactoryCreator(textDriverFactory)

import { textButtonDriverFactory } from '../components/TextButton/TextButton.driver';
export const textButtonTestkitFactory = protractorUniTestkitFactoryCreator(textButtonDriverFactory)

import { tooltipDriverFactory } from '../components/Tooltip/Tooltip.protractor.driver';
export const tooltipTestkitFactory = protractorTestkitFactoryCreator(tooltipDriverFactory)

